[package]
name = "queue_sim"
version = "0.1.0"
authors = ["Marcel Enguehard <mengueha@cisco.com>"]

[dependencies]
rand = "0.5.5"
zipf = "4.0.0"
ordered-float = "1.0.1"
num-traits = "0.2"
statistical = "0.1.1"
bloomfilter = "0.0.12"
lru-cache = "0.1.1"
